Resources:
  FamiliesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "familyId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "familyId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "touchbase-families"

  MembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "memberId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "memberId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "touchbase-members"
